flask_app/forms/dreForm.py
from wtforms import Form, StringField, validators


class DreForm(Form):
    tickerComplete = StringField(
        'ticker', [validators.Length(min=4, max=6)], id='ticker')
    #accept_tos = BooleanField('I accept the TOS', [validators.DataRequired()])

flask_app/views/dre.py
"""
O objetivo aqui é montar a DRE igual do fundamentei, sem as limitações impostas,
como a API do statusinvest é aberta, então temos os dados, a dificuldade está em
transpor as colunas de anos em linhas
"""
from flask import Flask, Blueprint, render_template, current_app, request

import requests
import json
import logging
import locale
import math
import datetime

from forms.dreForm import DreForm

bpDre = Blueprint('dre', __name__)


@bpDre.route('/dre')
def index():
    # form = DreForm(request.form)
    return render_template('dre.jinja')


@bpDre.route('/dre/search', methods=['GET'])
def search():
    current_app.logger.info("### DRE ###")
    if request.args.get('q') is None:
        return json.dumps([]), 200, {'content-type': 'application/json'}

    resp = requests.get(
        "https://statusinvest.com.br/home/mainsearchquery?q=" + request.args.get('q'))

    companyInfoJson = json.loads(resp.text)
    if companyInfoJson is None or len(companyInfoJson) == 0:
        return json.dumps({'Message': 'Nada foi encontrado aqui!'}), 400, {'content-type': 'application/json'}

    result = [dict({"value": stock['code'], "text": stock['nameFormated']})
              for stock in companyInfoJson if stock['type'] in (1, 12)]

    return json.dumps(result), 200, {'content-type': 'application/json'}


@bpDre.route('/dre/data', methods=['POST'])
def data():
    form = request.form
    # and form.validate():
    if form.get('tickerSelect') != "" and request.method == 'POST':
        if dreApi(form.get('tickerSelect')) is None:
            return render_template('dre.jinja', message='Dados não encontrados!')
        respJson = json.loads(dreApi(form.get('tickerSelect'))[0])
        return render_template('dre.jinja', form=form, stocks=respJson,
                               colnames=(respJson[0]).keys(), ticker=form.get('tickerSelect').upper())
        # if(respJson[1] == 400):
        #    return render_template('dre.jinja', errorMsg=respJson[0])
    return render_template('dre.jinja', form=request.form)


@bpDre.route('/api/dre/<companyId>')
def dreApi(companyId):
    current_app.logger.info("### DRE API ###")

    yearNow = datetime.datetime.now().year
    callUrl = "https://statusinvest.com.br/acao/getdre?"
    callUrl += "code=" + companyId
    callUrl += "&type=0&range.min=2000"
    #callUrl += "&range.max=" + str(yearNow)

    resp = requests.get(callUrl)
    dreDataJson = json.loads(resp.text)
    if len(dreDataJson) == 0:
        return

    grid = (dreDataJson['data'])['grid']

    locale.setlocale(locale.LC_MONETARY, '')

    ''' iniciando com a coluna dos anos, nos dados retornados pelo
        statusinvest, eles tem um lista propria, separada do resto dos dados
    '''
    (dreDataJson['data'])['years'].sort(reverse=True)
    ''' copiando os anos ordenados do maior para o menor, o formato é uma lista
        de dict, porque é de facil aceitação pela biblioteca json
    '''
    finalData = [dict({'year': [year, "#000000"]})
                 for year in (dreDataJson['data'])['years']]
    # inserindo TTM no inicio da lista
    finalData.insert(0, dict({'year': ['TTM', "#000000"]}))

    ignoreKeys = ['Custos - (R$)', 'Lucro Bruto - (R$)', 'Despesas Receitas Operacionais - (R$)',
                  'Amortização Depreciação', 'EBIT - (R$)', 'Resultado não operacional - (R$)',
                  'Impostos - (R$)', 'Lucro atribuído a Controladora', 'Lucro atribuído a Não Controladores',
                  'Dívida Bruta - (R$)', 'ROIC - (%)', 'Margem Bruta - (%)', 'Margem Ebitda - (%)']

    callUrl = "https://statusinvest.com.br/acao/getbsactivepassivechart?"
    callUrl += "companyName=" + companyId
    callUrl += "&type=2"

    respPassive = requests.get(callUrl)
    passiveDataJson = json.loads(respPassive.text)

    for idxLine, line in enumerate(passiveDataJson):
        valueTmp = (str(line['patrimonioLiquido']))[:-6]
        value = ('%.2f' % float(valueTmp[:-2] + '.' + valueTmp[2:])) + "M"
        color = "#cc0000" if value.startswith("-") else "#2b1d0e"
        if idxLine == 0:
            finalData[0].update(
                {'Patrimônio Líquido': [value, color]})
        for idx, data in enumerate(finalData):
            if (data['year'])[0] == line['year']:
                finalData[idx].update(
                    {'Patrimônio Líquido': [value, color]})

    ''' vamos para a lista contendo os dados, será necessario
        transpor os dados de colunas para linhas
    '''
    for idx, content in enumerate(grid):
        # print(idx, content['isHeader'])
        ''' a primeira entrada da grid é o header, não precisamos dela,
            pois iremos pega-lo mais a frente
        '''
        if content['isHeader']:
            continue
        columns = content['columns']
        colName = ''
        countDictItems = 0

        for idxCol in range(0, len(columns)-1, 1):
            col = columns[idxCol]
            # indice 0 é o nome da coluna
            if idxCol == 0:
                # current_app.logger.debug(f'{idxCol} - {columns[idxCol]}')
                colName = col['value'].replace("/", "\x20")
                continue
            ''' indices com nome de coluna = DATA são os valores anuais, não
                temos interesse em percentuais de crescimento ano a ano
            '''
            if 'DATA' in col['name'] and colName not in ignoreKeys:
                # current_app.logger.debug(
                #    f'{idxCol} - {countDictItems} - {finalData[countDictItems]}')
                value = (col['value']).replace("\x20", "")
                if value == "-":
                    color = "#000000"
                elif "(%)" in colName:
                    color = "#cc0000" if value.startswith("-") else "#505050"
                elif "CAPEX - (R$)" in colName:
                    color = "#000000"
                elif "Dívida Líquida - (R$)" in colName:
                    color = "#228b22" if value.startswith("-") else "#cc0000"
                elif "Dívida Líquida Ebitda" in colName:
                    valueColor = float(value.replace(
                        ".", "").replace(",", "."))
                    color = "#228b22" if valueColor < 2 else \
                        "#cc0000" if valueColor > 3 else "#d4af37"
                else:
                    color = "#cc0000" if value.startswith("-") else "#228b22"

                finalData[countDictItems].update({colName: [value, color]})
                countDictItems += 1

        # stock['price'] = locale.currency(stock['price'])
        # stock['vpa'] = '%.2f' % stock['vpa']
        # stock['lpa'] = '%.2f' % stock['lpa']
        # stock['val_Intrinseco'] = locale.currency(stock['val_Intrinseco'])

    ignoreCashKeys = ['Caixa Gerado nas Operações - (R$)', 'Saldo Inicial de Caixa e Equivalentes - (R$)',
                      'Aumento de Caixa e Equivalentes - (R$)', 'Variação Cambial de Caixa e Equivalentes - (R$)',
                      'Variações nos Ativos e Passivos - (R$)', 'Depreciação e Amortização - (R$)',
                      'Lucro Líquido - (R$)', 'Equivalência Patrimonial - (R$)',
                      'Caixa Líquido Atividades de Investimento - (R$)']

    callUrl = "https://statusinvest.com.br/acao/getfluxocaixa?"
    callUrl += "code=" + companyId
    callUrl += "&type=0"

    respCash = requests.get(callUrl)
    cashDataJson = ((json.loads(respCash.text))['data'])['grid']

    for idx, content in enumerate(cashDataJson):
        if content['isHeader']:
            continue
        columnsList = content['columns']
        colName = ''
        countDictItems = 0
        for idxCol, col in enumerate(columnsList):
            if idxCol == 0:
                colName = col['value'].replace("/", "\x20")
                continue
            if 'DATA' in col['name'] and colName not in ignoreCashKeys:
                # current_app.logger.debug(
                #    f'{idxCol} - {countDictItems} - {finalData[countDictItems]}')
                value = (col['value']).replace("\x20", "")
                color = "#000000"
                if "Caixa Líquido Atividades de Financiamento - (R$)" in colName:
                    color = "#000000" if value.startswith("-") else "#cc0000"
                elif "Caixa Líquido Atividades Operacionais - (R$)" in colName:
                    color = "#cc0000" if value.startswith("-") else "#000000"

                if countDictItems == 0:
                    finalData[0].update({colName: [value, color]})
                    #finalData[0].find('Caixa Líquido Atividades Operacionais - (R$)')
                if countDictItems+1 < len(finalData):
                    finalData[countDictItems +
                              1].update({colName: [value, color]})
                    countDictItems += 1

    for idx, line in enumerate(finalData):
        fco = line.get(
            'Caixa Líquido Atividades Operacionais - (R$)', ['0', '#000000'])
        fco = float(0 if fco[0] == '-' or fco[0] ==
                    '' else fco[0].replace(".", "").replace(",", ".").replace("M", ""))
        capex = line.get('CAPEX - (R$)', ['0', '#000000'])
        capex = float(0 if capex[0] == '-' or capex[0] ==
                      '' else capex[0].replace(".", "").replace(",", "."))
        finalData[idx].update({'FCL CAPEX': [('%.2f' % (
            fco - capex)) + "M", '#228b22' if (fco - capex) >= 0.0 else '#cc0000']})

    callUrl = "https://statusinvest.com.br/acao/payoutresult?"
    callUrl += "code=" + companyId
    callUrl += "&type=2"

    respPayout = requests.get(callUrl)
    payoutDataJson = json.loads(respPayout.text)

    # print(payoutDataJson)
    if len((payoutDataJson['chart'])['series']) == 0:
        return json.dumps(finalData), 200, {'content-type': 'application/json'}

    percentualData = ((payoutDataJson['chart'])['series'])['percentual']
    proventosData = ((payoutDataJson['chart'])['series'])['proventos']
    yearsData = (payoutDataJson['chart'])['category']

    percentualData.reverse()

flask_app/views/graham.py
'''
http://investidor-inteligente.com/benjamin-graham-margem-de-seguranca-investimento-acoes/

Margem de segurança, comparação P/L invertido com a taxa selic, P/L invertido tem que ser maior.

O objetivo é rankear as ações pelo desconto em relação ao preço. Graham, o pai
do value investing, descreveu em seu livro, O investidor inteligente, uma
formula para determinar o valor intriseco de uma ação, ou seja seu valor real
em determinado momento.

sqrt(22.5 * vpa * lpa)

Essa formula foi usada por muito tempo por Warren Buffet, pupilo de Graham,
entretanto hoje ela é questionada, pois empresas de tecnologia costumam ter
pouco patrimonio liquido, distorcendo o resultado da formula.

https://cabotwealth.com/daily/value-investing/benjamin-grahams-value-stock-criteria/
http://seuguiadeinvestimentos.com.br/a-tecnica-de-investimento-de-benjamin-graham-ii/
https://smarttinvest.com/carteiras-recomendadas-old/dh-graham/
http://www.acaoereacao.net/defens.html

CRITERIOS AVANÇADOS:
----
Investidor Sardinha:
Cagr 5% roe 5%
Abaixo valor intrínseco
Líder setor
Dividendos 10 anos
Lucros 10 anos
Perenidade 30 anos 
----
Ação e Reação:
1. Companhias proeminentes em seus setores.
2. Vendas anuais substanciais: acima de US$ 250 milhões.
3. Sólida posição financeira: Liquidez Corrente de pelo menos 1,00 e relação Dívida Líquida/Patrimônio Líquido máxima de 50%.
4. Estabilidade de lucro: lucro e dividendos contínuos durante pelo menos 12 anos.
5. Crescimento de lucro: aumento de pelo menos 4% aa em termos reais, usando as médias dos 3 anos no início e no fim de um período de 12 anos.
6. Preço/Lucro histórico moderado: o preço atual da ação, dividido pelo lucro médio dos últimos 3 anos (corrigidos pela inflação), não deve exceder 15x.
A recomendação básica de Graham é que o Lucro/Preço médio (o inverso do Preço/Lucro médio) da carteira seja pelo menos igual à taxa de juros oferecida por bônus de boa qualidade. Hoje a NTN-B de 9 anos oferece juros de 5,1% aa em termos reais que equivale a um Lucro/Preço de 19,6x.
7. Preço/Patrimônio Líquido moderado: o indicador não deve ultrapassar 150%. Mas, seguindo Graham, aceitamos um Preço/Patrimônio Líquido maior de 150% (ou 1,5) se o produto de Preço/Patrimônio Líquido x Preço/Lucro é menor que 22,50.
'''
from flask import Flask, Blueprint, render_template, current_app, request

import requests
import json
import logging
import locale
import math

bpGraham = Blueprint('graham', __name__)


@bpGraham.route('/graham', methods=['POST', 'GET'])
def index():
    current_app.logger.info("### graham ###")
    checkSelected = False
    if request.method == 'POST':
        checkSelected = True if 'advanced' in request.form else False
    respJson = json.loads(grahamApi(checkSelected)[0])
    return render_template('graham.jinja', stocks=respJson, colnames=(respJson[0]).keys(), checkSelected=checkSelected)


@bpGraham.route('/api/graham/<advanced>')
def grahamApi(advanced):
    current_app.logger.info("### graham ###")
    locale.setlocale(locale.LC_MONETARY, '')
    resp = None

    if advanced:
        resp = requests.get(
            "https://statusinvest.com.br/category/advancedsearchresult?CategoryType=1&search={'dividaliquidaPatrimonioLiquido':{'Item1':null,'Item2':0.5},'liquidezCorrente':{'Item1':1,'Item2':null}, 'lucros_Cagr5':{'Item1':5,'Item2':null},'liquidezMediaDiaria':{'Item1':200000,'Item2':null},'roe':{'Item1':5,'Item2':null}}")
    else:
        resp = requests.get(
            "https://statusinvest.com.br/category/advancedsearchresult?CategoryType=1&search={'liquidezMediaDiaria':{'Item1':200000,'Item2':null}}")

    stocksJson = json.loads(resp.text)

    for idx in range(len(stocksJson)-1, -1, -1):
        stock = stocksJson[idx]
        if "vpa" not in stock or "lpa" not in stock or "price" not in stock:
            stocksJson.pop(idx)
            continue
        if float(stock["vpa"]) <= 0 or float(stock["lpa"]) <= 0:
            stocksJson.pop(idx)
            continue

        stock['dl_Pl'] = stock['dividaliquidaPatrimonioLiquido'] if 'dividaliquidaPatrimonioLiquido' in stock else 0
        stock['liq_Corr'] = stock['liquidezCorrente'] if 'liquidezCorrente' in stock else 0

        stock['lucros_Cagr5'] = '%.2f' % round((
            0 if 'lucros_Cagr5' not in stock else stock['lucros_Cagr5']), 2)
        stock['val_Intrinseco'] = math.sqrt(
            22.5 * float(stock['vpa']) * float(stock['lpa']))
        stock['desconto'] = float(
            stock['val_Intrinseco']) - float(stock['price'])

        stock['margem'] = ((float(
            stock['val_Intrinseco']) - float(stock['price'])) / float(stock['val_Intrinseco'])) * 100

        for key in ['companyId', 'roic', 'p_VP', 'p_Ebit', 'p_Ativo', 'margemBruta', 'margemEbit',
                    'margemLiquida', 'p_SR', 'p_CapitalGiro', 'p_AtivoCirculante', 'giroAtivos', 'roa',
                    'dividaLiquidaEbit', 'pl_Ativo', 'passivo_Ativo', 'liquidezCorrente',
                    'peg_Ratio', 'receitas_Cagr5', 'liquidezMediaDiaria', 'p_L', 'eV_Ebit',
                    'valorMercado', 'dy', 'dividaliquidaPatrimonioLiquido']:
            stock.pop(key, None)

        # stock['dividaliquidaPatrimonioLiquido'] = '%.2f' % round(
        #    stock['dividaliquidaPatrimonioLiquido'], 2)
        stock['price'] = locale.currency(stock['price'])
        stock['vpa'] = '%.2f' % round(stock['vpa'], 2)
        stock['lpa'] = '%.2f' % round(stock['lpa'], 2)
        stock['val_Intrinseco'] = locale.currency(stock['val_Intrinseco'])
        stock['desconto'] = locale.currency(stock['desconto'])

        # 'lucros_Cagr5','liquidezCorrente','dividaliquidaPatrimonioLiquido',

    stocksJson.sort(key=lambda x: (x["margem"]), reverse=True)

    for stock in stocksJson:
        stock['margem'] = ('%.2f' % round(stock['margem'], 2)) + '%'

    return json.dumps(stocksJson), 200, {'content-type': 'application/json'}

flask_app/templates/base.html
<!doctype html>
<html lang="pt-BR">

<head>
    {% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
        <!-- Bootstrap CSS -->
        {{ bootstrap.load_css() }}
        {% endblock %}
        <title> bStonks </title>
    {% endblock %}
</head>

<body>
    <!-- Your page content -->
    {% block content %}{% endblock %}

    {% block scripts %}
    <!-- Optional JavaScript -->
    {{ bootstrap.load_js() }}
    {% endblock %}
</body>

</html>

flask_app/templates/base.jinja
{# ``base.html`` is the template all our other templates derive from. While
    Flask-Bootstrap ships with its own base, it is good form to create a custom
    one for our app, as it allows customizing some aspects.

    Deriving from bootstap/base.html gives us a basic page scaffoling.

    You can find additional information about template inheritance at

    http://jinja.pocoo.org/docs/templates/#template-inheritance
#}
{% extends "base.html" %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{# {% extends "bootstrap_responsive.html" %}
{% import "bootstrap_wtf.html" as wtf %} #}
{# 
{% block styles %}
    {{ super() }}
    <link rel="stylesheet"
         href="{{url_for('.static', filename='flask.css')}}">
{% endblock %} #}

{# We also set a default title, usually because we might forget to set one.
    In our sample app, we will most likely just opt not to change it #}

{# Finally, round things out with navigation #}
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" 
            data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" 
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">bStonks</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {{ render_nav_item('index','Home') }}
            {{ render_nav_item('greenblatt.index','Greenblatt') }}
            {{ render_nav_item('graham.index','Graham') }}
            {{ render_nav_item('srank.index','S-Rank') }}
            {{ render_nav_item('dre.index','DRE') }}
            {# {{ render_nav_item('imposto.imposto','IRPF') }} #}
            </ul>
        </div>   
    </nav>
{% endblock %}

flask_app/templates/dre.jinja
{% extends "base.jinja" %}

{% block styles %}
    {{ super() }}
    <style>
        .table-sm{
            font-size: 11px;
        }
    </style>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="
        https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js">
    </script>
    <script>
        $('.basicAutoSelect').autoComplete({
            resolverSettings: {
                url: '{{ url_for("dre.search") }}'
            },
            autoSelect: true,
            preventEnter: true
        });
        $('.basicAutoSelect').on('autocomplete.dd.hidden', function (evt) {
            evt.preventDefault(); 
            if($('.basicAutoSelect').val() === "")
                return
            $('form').submit();
	    });
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}

{% block content %}
   {{ super() }}
    <div class="jumbotron">
        <h1>Demonstrativo de resultado do exercício</h1>
        <form method="POST" action="{{ url_for('dre.data') }}">
            <select class="form-control basicAutoSelect" name="tickerSelect" 
            placeholder="Digite para buscar, ex: Ambev, Itau" autocomplete="off"></select>
        </form>
    </div>
    {% if errorMsg %}
    <div class="alert alert-info" role="alert">{{ errorMsg }}</div>
    {% endif %}
    <div class="mx-3">
        <div class="table-responsive-sm">
            <table class="table table-sm table-striped">
                <thead class="table-dark">
                    <tr>
                        {% if ticker %}
                        <th colspan="{{ colnames|length }}">{{ ticker }}</th>
                        {% endif %}
                    </tr>
                    <tr>
                        {% for col in colnames %}
                        <th scope="col">{{ col }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for stock in stocks %}
                    <tr>
                        {% for col in colnames %}
                            {% if "year" in col %}
                            <td class="text-left" style="font-weight:bold">{{ (stock[col])[0] }}</td>
                            {% elif stock[col] is defined %}
                            <td class="text-right" style="font-weight:bold;color:{{ (stock[col])[1] }}">
                                {{ (stock[col])[0] }}</td>
                            {% else %}
                            <td class="text-right" style="font-weight:bold">{{ "-" }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>    
    </div>
{% endblock %}

flask_app/templates/graham.jinja
{% extends "base.jinja" %}

{% block content %}
   {{ super() }}
    <div class="jumbotron">
        <h1>Ações mais descontadas pela fórmula de Graham</h1>
        <h6>* Removidas empresas com liquidez média diária menor que 200 mil reais.</h6>
        <h6>* Removidas empresas com VPA e LPA negativos.</h6>

        <div class="card bg-dark text-white">
            <div class="card-body">
                <div class="custom-control custom-switch">
                    <form method="POST" action="{{ url_for('graham.index') }}">
                        <input class="custom-control-input" type="checkbox" id="advanced" name="advanced" value="advanced" {% if checkSelected %} checked {% endif %} 
                        onclick="this.form.submit();">
                        <label class="custom-control-label" for="advanced">Aplicar critérios avançados</label>
                    </form>
                </div>
                <h6></h6>
                <h6>* CAGR dos lucros superior a 5% a.a. nos ultimos 5 anos.</h6>
                <h6>* ROE maior que 5%.</h6>
                <h6>* Liquidez corrente maior que 1.</h6>
                <h6>* Relação Dívida líquida / Patrimônio líquido maxima de 50%.</h6>
            </div>
        </div>

    </div>
    <div class="mx-3">
        <div class="table-responsive">
            <table class="table table-sm table-striped">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        {% for col in colnames %}
                        <th scope="col">{{ col }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for stock in stocks %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        {% for col in colnames %}
                            {% if "companyName" in col or "ticker" in col %}
                            <td class="text-left">{{ stock[col] }}</td>                             
                            {% else %}
                            <td class="text-right">{{ stock[col] }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>    
    </div>
{% endblock %}

flask_app/templates/greenblatt.jinja
{% extends "base.jinja" %}

{% block content %}
   {{ super() }}
    <div class="jumbotron">
        <h1>Ranking pela fórmula de Greenblatt</h1>
        <h6>* Removidas empresas com liquidez média diária menor que 200 mil reais.</h6>
        <h6>* Removidas empresas com Valor de mercado menor que 50 milhões de reais.</h6>
        <h6>* Removidas empresas com P/L, ROE, EV/EBIT e ROIC negativos.</h6>
        <h6>* Bancos não possuem ROIC e são automaticamente excluídos da opção "EV/EBIT e ROIC".</h6>

        <form method="POST" action="{{ url_for('greenblatt.index') }}">
            <select class="form-control" name="typeSelect" onchange="this.form.submit();" autocomplete="off">
                <option value="cat1" {% if "cat1" in selectedType %} selected {% endif %}>PL e ROE</option>
                <option value="cat2" {% if "cat2" in selectedType %} selected {% endif %}>EV/EBIT e ROIC</option>
            </select>
        </form>
    </div>
    <div class="mx-3">
        <div class="table-responsive">
            <table class="table table-sm table-striped">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        {% for col in colnames %}
                        <th scope="col">{{ col }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for stock in stocks %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        {% for col in colnames %}
                            {% if "companyName" in col or "ticker" in col %}
                            <td class="text-left">{{ stock[col] }}</td>
                            {% else %}
                            <td class="text-right">{{ stock[col] }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>    
    </div>
{% endblock %}

flask_app/templates/index.jinja
{% extends "base.jinja" %}

{% block content %}
   {{ super() }}
    <div class="jumbotron">
         <h1>Bem vindo ao bStonks</h1>
         <p>O objetivo é rankear ações pela fórmula de Joel Greenblatt.</p>
         <p>Futuramente poderemos verificar se o preço de determinada ação está 
            descontada em relação ao seu valor intrinseco:</p>
         <ul> 
            <li>Valuation por fluxo de caixa descontado</li>
            <li>Fórmula de Benjamin Graham</li>
            <li>Modelo de Gordon</li>
         </ul> 
    </div>
{% endblock %}

flask_app/templates/srank.jinja
{% extends "base.jinja" %}

{% block content %}
   {{ super() }}
    <div class="jumbotron">
        <h1>Ranking pela fórmula S-Rank</h1>
        <h6>* Removidos Fundos Imobiliários com liquidez média diária menor que 200 mil reais.</h6>
        <h6>* Removidos Fundos Imobiliários de Incorporação e Desenvolvimento.</h6>
        <h6>* Removidos Fundos Imobiliários com P/VP e DY zerados ou negativos.</h6>
        <br/>
        <h6>* Obs1: StatusInvest não tem DY dos últimos 5 anos, foi considerado o DY atual.</h6>
        <h6>* Obs2: StatusInvest não tem Data de início do Fundo de forma acessível, filtro de 1 ano de existência não aplicado.</h6>
    </div>
    <div class="mx-3">
        <div class="table-responsive">
            <table class="table table-sm table-striped">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        {% for col in colnames %}
                        <th scope="col">{{ col }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for stock in stocks %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        {% for col in colnames %}
                            {% if "companyName" in col or "ticker" in col %}
                            <td class="text-left">{{ stock[col] }}</td>
                            {% else %}
                            <td class="text-right">{{ stock[col] }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>    
    </div>
{% endblock %}